#! /bin/bash

#Setup arguments
psql_host=$1
port=$2
db_name=$3
user_name=$4
password=$5i

lscpu_out=`lscpu`

get_host_id(){

}

get_memory_free (){
  
}

get_cpu_idel () {
  
}

#Helper founction
get_lscpu_value(){
  pattern=$1
  value=$(echo "$lscpu_out" | egrep "$pattern" | awk -F':' '{print $2}' | xargs)
  echo "value=$value"
}

get_cpu_kernal(){
  
}

get_disk_io(){
  
}

get_disk_available(){
  
}


#Step1:parse data and setup variables
timestamp=$(date "+%Y-%m-%d %H:%M:%S")
get_host_id
get_memory_free
get_cpu_idel
get_cpu_kernel
get_disk_io
get_disk_available

#Step2:construct INSERT statement
insert_stmt=$(cat <<-END
INSERT INTO host_info ("timestamp", host_id, memory_free, cpu_idel, cpu_kernel, disk_io, disk_available) VALUES ('${timestamp}', ${host_id}, '${memory_free}', '${cpu_idel}', '${cpu_kernel}', ${disk_io}, ${disk_available});
END
)
echo insert_stmt

#Step3:Execute INSERT statement
export PGPASSWORD=$password
psql -h $psql_host -p $port -U $user_name -d $db_name -c "$insert_stmt"
sleep 1

#Step4:Save host_id generated by PSQL table to a local file
host_id=`psql -h localhost -U postgres host_agent -c "select id from host_usage where hostname='${hostname}'"|tail -3|head -1|xargs`
echo $host_id > ~/host_id
cat ~/host_id
